### ISSUE TITLE
"This seems like a new account" loop

### ISSUE THREAD

**Issue by Aritz331** [domcloud/domcloud#21]
![image](https://user-images.githubusercontent.com/59333567/181374449-20cddd83-1d43-400a-96f2-208e56976bfa.png)
Every time I click it it reloads and uses another code (`?code=`). Nothing else happens.

**Comment by willnode** [comment]
Hey, thanks for spotting the bug. A fix has just rolled out but in case it is still stuck, there are other sign-up options using Google or email. I'll keep this open until I have tested it enough.

**Comment by Aritz331** [comment]
Now it logs out when I click the button and when I "log in" with GitHub again it displays the same message, and it loops forever again.

**Comment by willnode** [comment]
Sorry for that. I have tested and fixed it again. Should works from now.

**Comment by Aritz331** [comment]
Yes, it should works now!
![image](https://user-images.githubusercontent.com/59333567/182023816-5564fc2d-56ed-4272-94a0-95e35017cb49.png)
