### ISSUE TITLE
Auto Generated Names Aren't Safe

### ISSUE THREAD

**Issue by devarshishimpi** [domcloud/domcloud#24]
![image](https://user-images.githubusercontent.com/43378923/187244750-8e3bfd74-f78d-4872-afb9-c8a767c33ff6.png)

**Comment by devarshishimpi** [comment]
I was deploying A Host and Found this in the username ( Auto Generated )
Please look through it.

Thanks.

**Comment by willnode** [comment]
You can change it. It's there because some people just simply click next without even reading, and they would be mad if it's interrupted there, just because the username is blank. Any better UI/UX suggestion?

**Comment by 06000208** [comment]
Though I can't know devarshi's intent, they may have meant that the randomly generated "babyish-blood" isn't safe for professional/work environments.

**Comment by devarshishimpi** [comment]
> Though I can't know devarshi's intent, they may have meant that the randomly generated "babyish-blood" isn't safe for professional/work environments. If that's the case, updating the word lists being used would resolve this.

@06000208 Hey, Yea I meant that. It's safe but like, blood and similar words??? Why??? But thanks for the updates

**Comment by devarshishimpi** [comment]
@06000208 I found your username is your github profile of Discord, will send a friend request with username "lil.dev" I don't remember hash right now 😅

**Comment by devarshishimpi** [comment]
> This one seems safe enough, but maybe too much: https://github.com/andreasonny83/unique-names-generator

Yep I think this should work, Do let me know about the updates for the same. Also Privacy And Security First!!!!

Mostly everyone will change the default random names, so I don't think overlapping would be an issue, there are more libraries out there for it.

**Comment by willnode** [comment]
Unsafe words are removed. Thanks.
