### ISSUE TITLE
NYC server will go maintenance mode 

### ISSUE THREAD

**Issue by willnode** [domcloud/domcloud#26]
Because the storage is almost full, `nyc.domcloud.id` will go offline at 19:00 (NYT time) tomorrow (Oct 25, 2022) for about 15 minutes. Nginx service will be turned off to avoid data loss.

**Comment by devarshishimpi** [comment]
@willnode Is it complete?

**Comment by willnode** [comment]
it's done

**Comment by devarshishimpi** [comment]
Great
