### ISSUE TITLE
Use more fine grained github access

### ISSUE THREAD

**Issue by jinyus** [domcloud/domcloud#30]
The app is request read/write permission for all private repos. I don't need to explain why this is dangerous, I should be able to grant access to only 1 repo.

**Comment by willnode** [comment]
Still a work in progress.

Currently, the easiest way to get private repo access is to ask for `private_repo` scope out of the existing GitHub OAuth token, but it can't be fine-grained... Unless I'm willing to go deep dive into creating GitHub apps.

That was the answer before four months ago... Recently GitHub has PATs that may fine-grain access tokens to specific repo... I might make use of that.

https://github.blog/changelog/2022-10-18-introducing-fine-grained-personal-access-tokens/

**Comment by willnode** [comment]
This looks like gonna be postponed for quite a long time.

Closest solution right now, is use GitHub Action. This doesn't require private Git Access, and work flawlessly on private orgs repo.

Documented here: https://github.com/domcloud/recipes#webhook

You still need to bring your own API key via Git remote URL in the server though, if the repo is private.

**Comment by willnode** [comment]
Now it's recommended to grant individual repo using deploy keys. It's always possible in the past but now the UI will help you: https://twitter.com/domcloud_co/status/1693249022247772525

We're explaining this in the docs: https://domcloud.co/docs/integration/github#secure-way-with-deploy-keys
