### ISSUE TITLE
A typo on website?

### ISSUE THREAD

**Issue by xjzh123** [domcloud/domcloud#33]
https://domcloud.co/#:~:text=From%20stratch%2C%20or%20existing%20repo.
https://domcloud.co/#:~:text=either%20from%20stratch%20or%20from%20your%20existing%20repo.

I find the word stratch likely to be a typo of scratch.

**Comment by xjzh123** [comment]
I also found 
https://domcloud.co/docs/features/runner/#:~:text=runner%20script%20is-,open%20sourced,-.%20More%20in%20depth

this link is to https://github.com/domcloud/brodge , should it be bridge

**Comment by willnode** [comment]
Thank you!
