### ISSUE TITLE
Don't delete my data!

### ISSUE THREAD

**Issue by dullbananas** [domcloud/domcloud#45]
I want a storage limit system that doesn't delete my home directory without warning.

Either let the data be accessible for at least 24 hours and send an email warning, or prevent disk writes that exceed the limit.

~~I will try to get my backend running on another free service before you fix this. If you fix it fast enough, then I will use dom cloud.~~

**Comment by willnode** [comment]
Current storage limit system will not delete your data unless you're on the free plan and it's grown 3x of the limit (4.5GB to be exact). Otherwise, it only disables your website from being publicly accessed.

**Comment by dullbananas** [comment]
Fine i'll do it myself

**Comment by willnode** [comment]
Other thing to note.. Most people got their website deleted because they haven't login in more than 2 month. It's either log in on each month or get enough monthly traffic (50 MB or more to be exact) or purchasing a paid plan to indicate one's account is still active.

**Comment by willnode** [comment]
I'm pretty sure that email warning is working. It's just that if it is over-capacitated, the website is disabled, in that case just remove some files and trigger the recalculation again: https://domcloud.co/blog/updating-os-across-servers#force-recalculation-of-disk-usage
