### ISSUE TITLE
*.domcloud.io domain (was) on hold

### ISSUE THREAD

**Issue by willnode** [domcloud/domcloud#58]
So I got an email that `domcloud.io` is currently suspended on the domain level because it contains phishing content, without being contacted first.

There's nothing I can do currently until it gets resolved by them. Discussions are currently in place.

Update: Solved, read below.

**Comment by willnode** [comment]
Additional clarification: If you want to get this resolved quickly, please use your own domain.

If within a week we don't get this resolved, there's a high chance we have to buy another domain, with stricter requirements for free users.

**Comment by willnode** [comment]
Edited https://domcloud.co/docs/features/dns 

The official name server changed from

```
nsp.domcloud.io
nss.domcloud.io
```
to

```
nsp.domcloud.co
nss.domcloud.co
```

If you have custom domain you need to change the name server and wait for couple of hours.

**Comment by lbrdt** [comment]
Hi, so sorry for the domain being on hold. I hope you get it sorted quickly. 

I am trying to get domcloud to work with my subdomain on my own domain but the [documentation](https://domcloud.co/docs/features/dns) for using subdomain seems confusing. It is focused on a root domain.

I pointed my subdomain to `nyc.domcloud.id` for `CNAME` as displayed on dashboard, enabled dns with deployment script, but the subdomain now points to a webserver that shows a `Welcome to Express` page. And it's only `http` not `https`

![image](https://i.ibb.co/dmQ9qkY/image.png)

**Comment by willnode** [comment]
> the subdomain now points to a webserver that shows a Welcome to Express page

That's not your website? 

> And it's only http not https

You can ask for renew certificate. Use Check Connection tab.

You can get better help using telegram chat.

**Comment by ArturoHDZG** [comment]
What happens to those of us who do not have custom domain? Will we have to wait or is there a solution?

**Comment by willnode** [comment]
Next 24 hours I will provide an alternative domain for a temporary solution.

**Comment by lbrdt** [comment]
> That's not your website?

no it is not. I will wait for the alternative domain to be available. Thanks!

**Comment by willnode** [comment]
Update: `domcloud.io` has been lifted from being on hold 🎉 

However, this is a last warning. So, there's a change.

From today all domains under `*.domcloud.io` are randomized with 7 readable alphabet characters. This can't be explicitly chosen anymore. If you need a personalized domain name, please buy one. 

To point your domain to us, change its name servers as in this documentation: https://domcloud.co/docs/features/dns

The DNS change is still propagating. `domcloud.io` will live within a couple of hours. After that I consider this issue is done.

**Comment by willnode** [comment]
`.domcloud.io` is banned again, permanently.

Looking for alternative domain name, any ideas?

**Comment by ArturoHDZG** [comment]
Oh God! Maybe you can improve security filters to prevent to malicious users use the service to create phishing's websites, for example, filter fake pages who redirects from big email providers, big store shops and well know cryptocurrency exchanges sites.

domcloud is a fancy name. Is it posible to keep it and change the .io for .net or something? Or you're looking for another name?

**Comment by willnode** [comment]
**Purchased and made available for paid users**: `*.domcloud.dev`.

For free users you can use external domain here: https://nic.eu.org/

**Comment by willnode** [comment]
For existing users who want to switch from `*.domcloud.io`, go to Admin -> Change Domain Name, then clear the domain field (❌ button). It will convert to `*.domcloud.dev`.

**Comment by ArturoHDZG** [comment]
How can i change subdomains names? none of mine works because of .io domain

**Comment by willnode** [comment]
Please change it to *.domcloud.dev like my instruction above, or send me email for personal guidance.

**Comment by jacklul** [comment]
Is it possible to use DDNS service like freemyip.com with the free tier? They allow specifying the IP for the subdomain via parameter.

**Comment by willnode** [comment]
> Is it possible to use DDNS service like freemyip.com with the free tier? They allow specifying the IP for the subdomain via parameter.

Seems that you need to hit freemyip.com/update inside the server, that's doable with curl/SSH.

**Comment by jacklul** [comment]
> Seems that you need to hit freemyip.com/update inside the server, that's doable with curl/SSH. Shoud be possible with free tier.

From the SSH freemyip.com seems to refuse connections on 443 and 80 but I managed to set it via the parameter for both IPv4 and IPv6.

The actual problem was the SSL certificate, installing Let's Encrypt one from the Webmin panel fixed it, everything works now!

**Comment by danielhvarela** [comment]
en julio pude hacer un deploy pero ahora se cayo el dns .nyc.dom.my.id/
