### ISSUE TITLE
nginx errors out during deployment on Singapore server

### ISSUE THREAD

**Issue by FrosT2k5** [domcloud/domcloud#73]
The deployment fails due to following error :
```
$> Error occured with exit code 1

nginx: [emerg] "listen" directive is not allowed here in /etc/nginx/conf.d/hupsuwa.sga.dom.my.id.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
```
Server - singapore
looks like it's due to some stale broken nginx config file.

**Comment by willnode** [comment]
Fixed. Thanks for reporting.

This issue pops up more often daily during my sleep. This is most likely because people deleting servers too fast. I have prevented them.
