### ISSUE TITLE
Could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by thirza258** [domcloud/domcloud#80]
Hello, i'm encountering an issue when trying to connect to my Domcloud PostgreSQL server. The error message is as follows:

OperationalError at /admin/login/
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Steps to Reproduce
1. Use virtualenv and fill in the database information in the environment variables based on the Domcloud DB information.
2. Set up the database with PostgreSQL and psycopg2 in the Django settings.
3. Deploy the application to Azure App Services.
4. Access the application using GET and POST requests.

Expected Behavior
I expect to be able to access the Django Admin or perform GET and POST requests from the Azure App Services to the Domcloud PostgreSQL server. When running the application locally, it works perfectly.

Actual Behavior
The connection attempt fails with the following error message:

OperationalError at /admin/login/
could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"

Screenshots or Logs
![image](https://github.com/user-attachments/assets/b4445b4d-c2b4-46e6-8b0b-18a212b9d8b2)

**Comment by willnode** [comment]
Hello, please connect to postgres not via unix socket but via IP address. Have you set the DB host to `127.0.0.1`?

**Comment by thirza258** [comment]
Hello, sorry for the late reply. I set the DB host to sga.domcloud.co and also tried using the IP address as the DB host. However, I still encountered the following error:

OperationalError at /admin/login/
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
	
![image](https://github.com/user-attachments/assets/e106895a-414f-44c4-9084-1ab4d3ee644c)

Could you help me resolve this issue?

**Comment by thirza258** [comment]
Sorry closing this issues, turns out the problem not come from the domcloud postgresql
